### PR TITLE
Fixed GraphBuilderMatcher and omitReachablePaths implementation

### PR DESCRIPTION
**Pull request by squishtronics**
Fixed error in GraphBuilderMatcher which incorrectly matched if either nodes or edges were equal, instead requiring both to match.

Changed omitReachablePaths implementation in GraphBuilderVisitor so that it remove edges after the graph is created, previously it would only detect duplicate paths if nodes were added in a specific order.

### CODE REVIEW

**Comment by squishtronics** [comment]
Regarding the test failures:
Four of them were integration tests. These failed due to the changes I have made to the omitReachablePaths implementation. The actual value after these changes seems to be correct IMO, therefore i have updated the expected values.

Ten of them were integration test. These failed now due to the fix made to the GraphBuilderMatcher. I have fixed most of them, because nothing was really wrong and only the expected value needed to be updated. Except for one.

**AggregatingGraphFactoryTest.excludeParentProjects**: for this test case I am not certain what the expected behavior should be. Any guidance on this would be appreciated. 

My impression is that it should create a graph based on child1, and with includeParentProjects=false, the final graph should only consist of child1. But with includeParentProjects=true, the final graph should also contain parent. 
This is not the case however so either my understanding of this functionality is incorrect or there is a bug in the code.

**Comment by ferstl** [comment]
Hi @squishtronics 
Thank you for your work. But I don't yet understand what problem you are trying to fix. Did you find a bug where the graph was not created correctly? If so, it would be nice to have an example to reproduce the problem.
I didn't have the time to look at the details of your changes yet but I looked at your changes in the expectations of the integration tests. Both are not correct. In `aggregate_transitive-excludes.txt` module-1 and its dependencies get resolved during the resolution of module-3, not of module-2. In `aggregate_graph.dot` module-a is not an optional dependency and module-test clearly has a dependency to module-a.
Generally, the traversal order of the dependencies is essential when creating the graph.

**Comment by squishtronics** [comment]
The main bug I am fixing is related to the reduceEdges property of the aggregate goal: 
https://ferstl.github.io/depgraph-maven-plugin/aggregate-mojo.html#reduceEdges
"Omit all edges that are already reachable via a different path in the dependency graph. "

Taking aggregate_transitive-excludes.txt as an example, i interpret this to mean that there should not be an edge between module-3 and module-1, because module-1 is reachable through module-2.

You can also see this in GraphBuildingVisitorTest.omitReachablePaths. You will need the fix to the GraphBuilderMatcher for the assertions to fail as well as change the order in which the nodes are visited. 
Just to be clear, the expected result is that there is no edge between A and D, because D can be reach from A through both B and C.

On master, the children of A are visited in the following order: B, C ,D. This order is ideal for the implementation on master, yet this order is not guaranteed in practice. A valid order is also D, B, C. If you change the test to reflect this, you will see it fail with the edge between A and D existing in the graph.

**Comment by ferstl** [comment]
> Taking aggregate_transitive-excludes.txt as an example, i interpret this to mean that there should not be an edge between module-3 and module-1, because module-1 is reachable through module-2.

module-1 should indeed not show up twice in the graph and it should appear under module-2 since this module is built before module-3. I'll take a look at that.
However, some of the adjustments in the test expectations/assertions are not correct, e.g. `aggregate_graph.dot`.

> I guess what I am getting at is that traversal order should not affect the final graph for the same maven project.

Aggregated graphs are a union of all modules' individual graphs (Maven does not have an overall dependency resolution of a multi-module project). The traversal order of an individual graph is not important but the reactor build order of the individual modules is.

**Comment by squishtronics** [comment]
Alright, i guess my changes had more impact than intended.
Could you also look at the AggregatingGraphFactoryTest.excludeParentProjects which i mentioned?

**Comment by ferstl** [comment]
I took a deeper look at the problem. The current solution where edges are omitted during graph traversal does indeed not work in some cases, e.g. in `GraphIntegrationTest#transitiveExcludes`. In such cases, we need to know the full graph in order to correctly remove redundant edges.

When removing edges we do also need to consider their "age". When there is more than one path from `A` to `B` in the graph, the path with the oldest edge to `B` should remain. This would accurately reflect how Maven resolves dependencies in a multi-module project. And I think that is also the reason why the solution in your PR produces not the correct results in some cases.

I documented the Problem in Issue #82 and started with a solution that looks quite promising so far. I hope I get it finished within the next couple of days.

**Comment by ferstl** [comment]
I released version 3.2.1 which fixes this problem. It should be on Maven Central within the next few hours.
Thank you for pointing out this problem and for your work!

**Pull request closed without merging**
